# Generated by Django 4.1.4 on 2022-12-14 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_house_pets_allowd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='pets_allowd',
            new_name='pets_allowed',
        ),
    ]
